In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
x = np.array(my_list)

In [4]:
type(x)

numpy.ndarray

In [5]:
# Numpy Matrices

In [6]:
my_matrix = [[1,2,3],[2,1,3],[3,1,2]]

In [7]:
my_matrix

[[1, 2, 3], [2, 1, 3], [3, 1, 2]]

In [8]:
x = np.array(my_matrix)

In [9]:
x

array([[1, 2, 3],
       [2, 1, 3],
       [3, 1, 2]])

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(1)

array([1.])

In [23]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.random.rand(5,4)

array([[0.91576879, 0.56660144, 0.3817917 , 0.55171838],
       [0.89282033, 0.64212751, 0.41601519, 0.63262408],
       [0.61945256, 0.79857973, 0.6158513 , 0.93077515],
       [0.50769214, 0.4144949 , 0.00802119, 0.84100878],
       [0.12132363, 0.7525949 , 0.01602484, 0.55036829]])

In [37]:
np.random.randin

<function RandomState.randint>

In [38]:
arr = np.arange(25)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr = np.random.randint(0,50,10)

In [41]:
ranarr

array([21, 22, 27, 15,  0, 44, 30,  1, 33, 45])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [44]:
arr.shape

(25,)